### ISSUE TITLE
Attempt to use on windows

### ISSUE THREAD

**Issue by Floyd2001** [zmahnoor14/MAW#37]
Please would you have tracks to use MAW on windows? With or without docker if possible?

**Comment by zmahnoor14** [comment]
you can use MAW within a docker container and it should work on windows because both MAW-R and MAW-Py are built on ubuntu images and your current platform doesn't matter. It is also currently going through further development stages because SIRIUS has been upgraded to SIRIUS5 which has not been integrated into MAW yet. 

you can still give MAW a try and refer to this GitHub issue for more information: 

[Think I can't connect to Sirius because of the new 5.0 version](https://github.com/zmahnoor14/MAW/issues/33)
